services:
  mssql:
    init: true
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
    ports:
      - 127.0.0.1:1433:1433

  ftp:
    build: ftp
    volumes:
      - ./ftp:/opt/app/data
    ports:
      - 127.0.0.1:2121:2121
      - 127.0.0.1:5000-5005:5000-5005

  main:
    profiles:
      - staging
    build: main
    init: true
    environment:
      - TZ=Europe/Berlin
      - PORT=3000
      - WEBSITE_BASE_URL=http://localhost:3000
      - WEBSITE_COOKIE_SESSION_KEYS=["some_insecure_staging_key"]
      - ADMIN_PORT=3002
      - ADMIN_BASE_URL=http://localhost:3002
      - ADMIN_COOKIE_SESSION_KEYS=["some_insecure_staging_key"]
      - MOBILE_PORT=3001
    volumes:
      - ./main/database:/opt/app/database
      - ./main/src/plugins/testApi.js:/opt/app/src/plugins/testApi.js
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 8111:8111
